package net.aetherteam.aether.client.renders;

import cpw.mods.fml.client.registry.RenderingRegistry;
import net.aetherteam.aether.client.models.ModelAechorPlant;
import net.aetherteam.aether.client.models.ModelAerbunny;
import net.aetherteam.aether.client.models.ModelAngel;
import net.aetherteam.aether.client.models.ModelCarrionSprout;
import net.aetherteam.aether.client.models.ModelCockatrice;
import net.aetherteam.aether.client.models.ModelHostEye;
import net.aetherteam.aether.client.models.ModelLabyrinthEye;
import net.aetherteam.aether.client.models.ModelMimic;
import net.aetherteam.aether.client.models.ModelMiniCloud;
import net.aetherteam.aether.client.models.ModelMoa;
import net.aetherteam.aether.client.models.ModelNewZephyr;
import net.aetherteam.aether.client.models.ModelPhyg1;
import net.aetherteam.aether.client.models.ModelPhyg2;
import net.aetherteam.aether.client.models.ModelSentryGolem;
import net.aetherteam.aether.client.models.ModelSentryGolemBoss;
import net.aetherteam.aether.client.models.ModelSheepuff1;
import net.aetherteam.aether.client.models.ModelSheepuff2;
import net.aetherteam.aether.client.models.ModelSheepuff3;
import net.aetherteam.aether.client.models.ModelSlider;
import net.aetherteam.aether.client.models.ModelSliderMimicHost;
import net.aetherteam.aether.client.models.ModelTempest;
import net.aetherteam.aether.client.models.ModelZephyroo;
import net.aetherteam.aether.client.renders.dungeon.RenderRewardItem;
import net.aetherteam.aether.entities.EntityAechorPlant;
import net.aetherteam.aether.entities.EntityAerwhale;
import net.aetherteam.aether.entities.EntityAetherCoin;
import net.aetherteam.aether.entities.EntityAetherLightning;
import net.aetherteam.aether.entities.EntityBattleSentry;
import net.aetherteam.aether.entities.EntityCarrionSprout;
import net.aetherteam.aether.entities.EntityCloudParachute;
import net.aetherteam.aether.entities.EntityCockatrice;
import net.aetherteam.aether.entities.EntityColdLightningBolt;
import net.aetherteam.aether.entities.EntityDartEnchanted;
import net.aetherteam.aether.entities.EntityDartGolden;
import net.aetherteam.aether.entities.EntityDartPoison;
import net.aetherteam.aether.entities.EntityFloatingBlock;
import net.aetherteam.aether.entities.EntityLightningKnife;
import net.aetherteam.aether.entities.EntityMimic;
import net.aetherteam.aether.entities.EntityNewZephyr;
import net.aetherteam.aether.entities.EntityNotchWave;
import net.aetherteam.aether.entities.EntityPoisonNeedle;
import net.aetherteam.aether.entities.EntityProjectileSentry;
import net.aetherteam.aether.entities.EntitySentry;
import net.aetherteam.aether.entities.EntitySentryGolem;
import net.aetherteam.aether.entities.EntitySheepuff;
import net.aetherteam.aether.entities.EntityTNTPresent;
import net.aetherteam.aether.entities.EntityTempest;
import net.aetherteam.aether.entities.EntityTempestBall;
import net.aetherteam.aether.entities.EntityTrackingGolem;
import net.aetherteam.aether.entities.EntityZephyr;
import net.aetherteam.aether.entities.EntityZephyrSnowball;
import net.aetherteam.aether.entities.EntityZephyroo;
import net.aetherteam.aether.entities.altar.EntityFakeItem;
import net.aetherteam.aether.entities.bosses.EntityCog;
import net.aetherteam.aether.entities.bosses.EntityHostEye;
import net.aetherteam.aether.entities.bosses.EntityLabyrinthEye;
import net.aetherteam.aether.entities.bosses.EntityMiniSlider;
import net.aetherteam.aether.entities.bosses.EntitySentryGuardian;
import net.aetherteam.aether.entities.bosses.EntitySlider;
import net.aetherteam.aether.entities.bosses.EntitySliderHostMimic;
import net.aetherteam.aether.entities.dungeon.EntityRewardItem;
import net.aetherteam.aether.entities.mounts.EntityAerbunny;
import net.aetherteam.aether.entities.mounts.EntityMoa;
import net.aetherteam.aether.entities.mounts.EntityPhyg;
import net.aetherteam.aether.entities.mounts.EntitySwet;
import net.aetherteam.aether.entities.npc.EntityBasicNPC;
import net.aetherteam.aether.oldcode.EntityMiniCloud;
import net.minecraft.client.entity.render.RenderMinecartMobSpawner;
import net.minecraft.client.renderer.entity.RenderMagmaCube;
import net.minecraft.src.bcp;

public class AetherEntityRenderers
{
    public static void registerEntityRenderers()
    {
        RenderingRegistry.registerEntityRenderingHandler(EntityAerwhale.class, new RenderAerwhale());
        RenderingRegistry.registerEntityRenderingHandler(EntityZephyr.class, new RenderZephyr());
        RenderingRegistry.registerEntityRenderingHandler(EntityZephyrSnowball.class, new RenderZephyrSnowball());
        RenderingRegistry.registerEntityRenderingHandler(EntityPhyg.class, new RenderPhyg(new ModelPhyg1(), new ModelPhyg2(), 0.0F));
        RenderingRegistry.registerEntityRenderingHandler(EntityAerbunny.class, new RenderAerbunny(new ModelAerbunny(), 0.3F));
        RenderingRegistry.registerEntityRenderingHandler(EntitySheepuff.class, new RenderSheepuff(new ModelSheepuff1(), new ModelSheepuff2(), new ModelSheepuff3(), 0.7F));
        RenderingRegistry.registerEntityRenderingHandler(EntityCloudParachute.class, new RenderCloudParachute());
        RenderingRegistry.registerEntityRenderingHandler(EntityFloatingBlock.class, new RenderFloatingBlock());
        RenderingRegistry.registerEntityRenderingHandler(EntityNotchWave.class, new RenderNotchWave(0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityCockatrice.class, new RenderCockatrice(new ModelCockatrice(), 1.0F));
        RenderingRegistry.registerEntityRenderingHandler(EntityMoa.class, new RenderMoa(new ModelMoa(), 1.0F));
        RenderingRegistry.registerEntityRenderingHandler(EntitySlider.class, new RenderSlider(new ModelSlider(0.0F, 12.0F), 1.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityAechorPlant.class, new RenderAechorPlant(new ModelAechorPlant(), 0.3F));
        RenderingRegistry.registerEntityRenderingHandler(EntityPoisonNeedle.class, new RenderPoisonNeedle());
        RenderingRegistry.registerEntityRenderingHandler(EntityDartGolden.class, new RenderDartGolden());
        RenderingRegistry.registerEntityRenderingHandler(EntityDartEnchanted.class, new RenderDartEnchanted());
        RenderingRegistry.registerEntityRenderingHandler(EntityDartPoison.class, new RenderDartPoison());
        RenderingRegistry.registerEntityRenderingHandler(EntityProjectileSentry.class, new RenderProjectileSentry());
        RenderingRegistry.registerEntityRenderingHandler(EntitySentry.class, new RenderSentry(new bcp(0), 0.2F));
        RenderingRegistry.registerEntityRenderingHandler(EntityBattleSentry.class, new RenderBattleSentry(new bcp(0), 0.2F));
        RenderingRegistry.registerEntityRenderingHandler(EntityLightningKnife.class, new RenderLightningKnife());
        RenderingRegistry.registerEntityRenderingHandler(EntityMimic.class, new RenderMimic(new ModelMimic(), 1.0F));
        RenderingRegistry.registerEntityRenderingHandler(EntityMiniCloud.class, new RenderMinecartMobSpawner(new ModelMiniCloud(0.0F, 20.0F), 0.35F));
        RenderingRegistry.registerEntityRenderingHandler(EntityTNTPresent.class, new RenderTNTPresent());
        RenderingRegistry.registerEntityRenderingHandler(EntityAetherLightning.class, new RenderMagmaCube());
        RenderingRegistry.registerEntityRenderingHandler(EntitySwet.class, new RenderSwet(new bcp(16), new bcp(0), 0.3F));
        RenderingRegistry.registerEntityRenderingHandler(EntityTrackingGolem.class, new RenderTrackingGolem(new ModelSentryGolem(), 1.0F));
        RenderingRegistry.registerEntityRenderingHandler(EntitySentryGolem.class, new RenderSentryGolem(new ModelSentryGolem(), 1.0F));
        RenderingRegistry.registerEntityRenderingHandler(EntitySentryGuardian.class, new RenderSentryGuardian(new ModelSentryGolemBoss(), 1.0F));
        RenderingRegistry.registerEntityRenderingHandler(EntitySliderHostMimic.class, new RenderSliderHostMimic(new ModelSliderMimicHost(), 1.0F));
        RenderingRegistry.registerEntityRenderingHandler(EntityHostEye.class, new RenderHostEye(new ModelHostEye(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityMiniSlider.class, new RenderMiniSlider(new ModelHostEye(), 1.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityAetherCoin.class, new RenderAetherCoin());
        RenderingRegistry.registerEntityRenderingHandler(EntityCog.class, new RenderCog());
        RenderingRegistry.registerEntityRenderingHandler(EntityLabyrinthEye.class, new RenderLabyrinthEye(new ModelLabyrinthEye(), 1.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityCarrionSprout.class, new RenderCarrionSprout(new ModelCarrionSprout(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityTempest.class, new RenderTempest(new ModelTempest()));
        RenderingRegistry.registerEntityRenderingHandler(EntityTempestBall.class, new RenderTempestBall());
        RenderingRegistry.registerEntityRenderingHandler(EntityNewZephyr.class, new RenderNewZephyr(new ModelNewZephyr()));
        RenderingRegistry.registerEntityRenderingHandler(EntityZephyroo.class, new RenderZephyroo(new ModelZephyroo(), 1.0F));
        RenderingRegistry.registerEntityRenderingHandler(EntityFakeItem.class, new RenderFakeItem());
        RenderingRegistry.registerEntityRenderingHandler(EntityRewardItem.class, new RenderRewardItem());
        RenderingRegistry.registerEntityRenderingHandler(EntityColdLightningBolt.class, new RenderColdLightning());
        RenderingRegistry.registerEntityRenderingHandler(EntityBasicNPC.class, new RenderNPC(new ModelAngel(), 1.0F));
    }
}

